[general]
prologue_file_path = "./prologue.jl"
library_name = "liboqs"
output_file_path = "./../src/C_API.jl"
module_name = "C_API"
# jll_pkg_name = "LibSparseIR_jll"
export_symbol_prefixes = ["OQS_"]
extract_c_comment_style = "doxygen"
